name: Keep Codespace Alive

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update -y
          sudo apt install -y gh

      - name: Keep Codespace alive
        run: |
          echo "Ping Codespace..."
          gh codespace list
          gh codespace ssh -c upgraded-space-halibut-6946x5vg77j6c5v5g
